using Amazon.DynamoDBv2.DataModel;

namespace TaparSolution.Models.DBTable
{
    [DynamoDBTable("Brands")]
    public class Brandtable
    {
        public string brand_oid { get; set; }
        public string Brand { get; set; }
        public string src { get; set; }

        public List<Brandtable> Fulllist()
        {
            return new List<Brandtable>()
            {
                //new Brandtable(){brand_oid="1",Brand="Bmw",src="https://www.iconsdb.com/icons/preview/black/bmw-xxl.png"},
                //new Brandtable(){brand_oid="2",Brand="Mitsubishi",src="https://cdn.icon-icons.com/icons2/1834/PNG/512/iconfindermitsubishilogo4141793-115967_115914.png"},
                //new Brandtable(){brand_oid="3",Brand="Mercedes",src="https://www.pngkey.com/png/detail/134-1345887_free-icons-png-mercedes-benz-logo.png"},

new Brandtable(){brand_oid="1",Brand="Abarth",src=""},
new Brandtable(){brand_oid="2",Brand="Alfa Romeo",src=""},
new Brandtable(){brand_oid="3",Brand="Arctic Cat",src=""},
new Brandtable(){brand_oid="4",Brand="Aston Martin",src=""},
new Brandtable(){brand_oid="5",Brand="ATV",src=""},
new Brandtable(){brand_oid="6",Brand="Audi",src=""},
new Brandtable(){brand_oid="7",Brand="Baic",src=""},
new Brandtable(){brand_oid="8",Brand="Bajaj",src=""},
new Brandtable(){brand_oid="9",Brand="Bentley",src=""},
new Brandtable(){brand_oid="10",Brand="Bestune",src=""},
new Brandtable(){brand_oid="11",Brand="BMC",src=""},
new Brandtable(){brand_oid="12",Brand="BMW",src=""},
new Brandtable(){brand_oid="13",Brand="BMW Alpina",src=""},
new Brandtable(){brand_oid="14",Brand="Brilliance",src=""},
new Brandtable(){brand_oid="15",Brand="Buick",src=""},
new Brandtable(){brand_oid="16",Brand="Bull Motors",src=""},
new Brandtable(){brand_oid="17",Brand="BYD",src=""},
new Brandtable(){brand_oid="18",Brand="Cadillac",src=""},
new Brandtable(){brand_oid="19",Brand="CFMOTO",src=""},
new Brandtable(){brand_oid="20",Brand="Changan",src=""},
new Brandtable(){brand_oid="21",Brand="Chery",src=""},
new Brandtable(){brand_oid="22",Brand="Chevrolet",src=""},
new Brandtable(){brand_oid="23",Brand="Chrysler",src=""},
new Brandtable(){brand_oid="24",Brand="Citroen",src=""},
new Brandtable(){brand_oid="25",Brand="Dacia",src=""},
new Brandtable(){brand_oid="26",Brand="Daewoo",src=""},
new Brandtable(){brand_oid="27",Brand="DAF",src=""},
new Brandtable(){brand_oid="28",Brand="Daihatsu",src=""},
new Brandtable(){brand_oid="29",Brand="Dayun",src=""},
new Brandtable(){brand_oid="30",Brand="Dnepr",src=""},
new Brandtable(){brand_oid="31",Brand="Dodge",src=""},
new Brandtable(){brand_oid="32",Brand="DongFeng",src=""},
new Brandtable(){brand_oid="33",Brand="Ducati",src=""},
new Brandtable(){brand_oid="34",Brand="FAW",src=""},
new Brandtable(){brand_oid="35",Brand="Ferrari",src=""},
new Brandtable(){brand_oid="36",Brand="Fiat",src=""},
new Brandtable(){brand_oid="37",Brand="Ford",src=""},
new Brandtable(){brand_oid="38",Brand="Foton",src=""},
new Brandtable(){brand_oid="39",Brand="GAC",src=""},
new Brandtable(){brand_oid="40",Brand="GAZ",src=""},
new Brandtable(){brand_oid="41",Brand="Geely",src=""},
new Brandtable(){brand_oid="42",Brand="Genesis",src=""},
new Brandtable(){brand_oid="43",Brand="GIBBS",src=""},
new Brandtable(){brand_oid="44",Brand="GMC",src=""},
new Brandtable(){brand_oid="45",Brand="Great Wall",src=""},
new Brandtable(){brand_oid="46",Brand="Haima",src=""},
new Brandtable(){brand_oid="47",Brand="Haojue",src=""},
new Brandtable(){brand_oid="48",Brand="Harley-Davidson",src=""},
new Brandtable(){brand_oid="49",Brand="Haval",src=""},
new Brandtable(){brand_oid="50",Brand="Honda",src=""},
new Brandtable(){brand_oid="51",Brand="Hongqi",src=""},
new Brandtable(){brand_oid="52",Brand="HOWO",src=""},
new Brandtable(){brand_oid="53",Brand="Hummer",src=""},
new Brandtable(){brand_oid="54",Brand="Hyundai",src=""},
new Brandtable(){brand_oid="55",Brand="IJ",src=""},
new Brandtable(){brand_oid="56",Brand="Infiniti",src=""},
new Brandtable(){brand_oid="57",Brand="Iran Khodro",src=""},
new Brandtable(){brand_oid="58",Brand="Isuzu",src=""},
new Brandtable(){brand_oid="59",Brand="Iveco",src=""},
new Brandtable(){brand_oid="60",Brand="JAC",src=""},
new Brandtable(){brand_oid="61",Brand="Jaguar",src=""},
new Brandtable(){brand_oid="62",Brand="Jeep",src=""},
new Brandtable(){brand_oid="63",Brand="Jetour",src=""},
new Brandtable(){brand_oid="64",Brand="Jianshe",src=""},
new Brandtable(){brand_oid="65",Brand="Jinbei",src=""},
new Brandtable(){brand_oid="66",Brand="JMC",src=""},
new Brandtable(){brand_oid="67",Brand="Jonway",src=""},
new Brandtable(){brand_oid="68",Brand="KamAz",src=""},
new Brandtable(){brand_oid="69",Brand="Kawasaki",src=""},
new Brandtable(){brand_oid="70",Brand="Kayo",src=""},
new Brandtable(){brand_oid="71",Brand="Khazar",src=""},
new Brandtable(){brand_oid="72",Brand="Kia",src=""},
new Brandtable(){brand_oid="73",Brand="KrAZ",src=""},
new Brandtable(){brand_oid="74",Brand="KTM",src=""},
new Brandtable(){brand_oid="75",Brand="Kuba",src=""},
new Brandtable(){brand_oid="76",Brand="LADA (VAZ)",src=""},
new Brandtable(){brand_oid="77",Brand="Lamborghini",src=""},
new Brandtable(){brand_oid="78",Brand="Land Rover",src=""},
new Brandtable(){brand_oid="79",Brand="Lexus",src=""},
new Brandtable(){brand_oid="80",Brand="Lifan",src=""},
new Brandtable(){brand_oid="81",Brand="Lincoln",src=""},
new Brandtable(){brand_oid="82",Brand="LuAz",src=""},
new Brandtable(){brand_oid="83",Brand="Mack",src=""},
new Brandtable(){brand_oid="84",Brand="MAN",src=""},
new Brandtable(){brand_oid="85",Brand="Maserati",src=""},
new Brandtable(){brand_oid="86",Brand="MAZ",src=""},
new Brandtable(){brand_oid="87",Brand="Mazda",src=""},
new Brandtable(){brand_oid="88",Brand="Mercedes",src=""},
new Brandtable(){brand_oid="89",Brand="Mercedes-Maybach",src=""},
new Brandtable(){brand_oid="90",Brand="MG",src=""},
new Brandtable(){brand_oid="91",Brand="Mini",src=""},
new Brandtable(){brand_oid="92",Brand="Minsk",src=""},
new Brandtable(){brand_oid="93",Brand="Mitsubishi",src=""},
new Brandtable(){brand_oid="94",Brand="Mondial",src=""},
new Brandtable(){brand_oid="95",Brand="Moskvich",src=""},
new Brandtable(){brand_oid="96",Brand="Muravey",src=""},
new Brandtable(){brand_oid="97",Brand="MV Agusta",src=""},
new Brandtable(){brand_oid="98",Brand="Nama",src=""},
new Brandtable(){brand_oid="99",Brand="Neoplan",src=""},
new Brandtable(){brand_oid="100",Brand="Nissan",src=""},
new Brandtable(){brand_oid="101",Brand="Oldsmobile",src=""},
new Brandtable(){brand_oid="102",Brand="Opel",src=""},
new Brandtable(){brand_oid="103",Brand="PAZ",src=""},
new Brandtable(){brand_oid="104",Brand="Peugeot",src=""},
new Brandtable(){brand_oid="105",Brand="Pontiac",src=""},
new Brandtable(){brand_oid="106",Brand="Porsche",src=""},
new Brandtable(){brand_oid="107",Brand="RAF",src=""},
new Brandtable(){brand_oid="108",Brand="Ravon",src=""},
new Brandtable(){brand_oid="109",Brand="Renault",src=""},
new Brandtable(){brand_oid="110",Brand="RKS",src=""},
new Brandtable(){brand_oid="111",Brand="Rolls-Royce",src=""},
new Brandtable(){brand_oid="112",Brand="Saipa",src=""},
new Brandtable(){brand_oid="113",Brand="Scania",src=""},
new Brandtable(){brand_oid="114",Brand="SEAT",src=""},
new Brandtable(){brand_oid="115",Brand="Setra",src=""},
new Brandtable(){brand_oid="116",Brand="Shacman",src=""},
new Brandtable(){brand_oid="117",Brand="Shaolin",src=""},
new Brandtable(){brand_oid="118",Brand="Skoda",src=""},
new Brandtable(){brand_oid="119",Brand="Smart",src=""},
new Brandtable(){brand_oid="120",Brand="Ssang Yong",src=""},
new Brandtable(){brand_oid="121",Brand="Subaru",src=""},
new Brandtable(){brand_oid="122",Brand="Suzuki",src=""},
new Brandtable(){brand_oid="123",Brand="Tatra",src=""},
new Brandtable(){brand_oid="124",Brand="Temsa",src=""},
new Brandtable(){brand_oid="125",Brand="Tesla",src=""},
new Brandtable(){brand_oid="126",Brand="Tofas",src=""},
new Brandtable(){brand_oid="127",Brand="Toyota",src=""},
new Brandtable(){brand_oid="128",Brand="Tufan",src=""},
new Brandtable(){brand_oid="129",Brand="UAZ",src=""},
new Brandtable(){brand_oid="130",Brand="Ural",src=""},
new Brandtable(){brand_oid="131",Brand="Vespa",src=""},
new Brandtable(){brand_oid="132",Brand="Volkswagen",src=""},
new Brandtable(){brand_oid="133",Brand="Volvo",src=""},
new Brandtable(){brand_oid="134",Brand="Vosxod",src=""},
new Brandtable(){brand_oid="135",Brand="Wild West",src=""},
new Brandtable(){brand_oid="136",Brand="XCMG",src=""},
new Brandtable(){brand_oid="137",Brand="Yadea",src=""},
new Brandtable(){brand_oid="138",Brand="Yamaha",src=""},
new Brandtable(){brand_oid="139",Brand="Yutong",src=""},
new Brandtable(){brand_oid="140",Brand="ZAZ",src=""},
new Brandtable(){brand_oid="141",Brand="ZIL",src=""},
new Brandtable(){brand_oid="142",Brand="Zongshen",src=""},
new Brandtable(){brand_oid="143",Brand="Zontes",src=""},
new Brandtable(){brand_oid="144",Brand="ZX Auto",src=""}
            };
        }
    }
}
